# This is a basic workflow to help you get started with Actions

# Somewhat based on https://github.com/ShadowMario/FNF-PsychEngine/blob/main/.github/workflows/main.yml

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4

      # Runs a single command using the runners shell
      - name: Haxeflixel Libraries Installer
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime
          haxelib run lime setup
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib install hxcpp-debug-server
          haxelib update hxcpp
          haxelib update lime
          haxelib update openfl
          haxelib update flixel
          haxelib update flixel-tools
          haxelib update hxcpp-debug-server
          
          haxelib list
        shell: cmd

        # yes i took this line from the fnf thing shut up
      - name: New Tag
        run: echo "${{github_run_id}}" > VERSION
      # back to things i understand
      - name: Build Game
        run: lime test windows -release
      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windowsGame
          path: export/release/windows/bin
